### ISSUE TITLE
Suggested rewrite for this sentence

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/careers-resume-work-experience#7]
This sentence is missing a period at the end:
"Instead of just listing a task, consider what did the task result in "

Suggested rewrite:
"Instead of just listing a task, consider this: What did the task result in?"

The next sentence is "What good or benefit did it drive?" so the colon makes sense before the list of these two items.

Thank you.

**Comment by maxwellbenton** [comment]
Fixed. Thank you @ValerieHMoore!
